// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAibEIfsV38cIxLmJ9aYii2HEuQbhBazFI',
    appId: '1:391319281811:web:a1343a8a6e59844b876d66',
    messagingSenderId: '391319281811',
    projectId: 'node-project-49c19',
    authDomain: 'node-project-49c19.firebaseapp.com',
    storageBucket: 'node-project-49c19.firebasestorage.app',
    measurementId: 'G-ESKECV8KW4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZWKsfYsJRcnLZmKQHieWuQO60fRS1Q8',
    appId: '1:391319281811:ios:e5443d7cca86d2c7876d66',
    messagingSenderId: '391319281811',
    projectId: 'node-project-49c19',
    storageBucket: 'node-project-49c19.firebasestorage.app',
    iosBundleId: 'com.example.ancilmediaadminpanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAibEIfsV38cIxLmJ9aYii2HEuQbhBazFI',
    appId: '1:391319281811:web:a1343a8a6e59844b876d66',
    messagingSenderId: '391319281811',
    projectId: 'node-project-49c19',
    authDomain: 'node-project-49c19.firebaseapp.com',
    storageBucket: 'node-project-49c19.firebasestorage.app',
    measurementId: 'G-ESKECV8KW4',
  );
}
