// import 'package:flutter/material.dart';
// import 'package:provider/provider.dart';
// import 'package:flutter_web_plugins/flutter_web_plugins.dart';
//
// import 'View/Login_page.dart';
// import 'Services/api_client.dart';
// import 'View_model/Authentication_state.dart';
// import 'View_model/Drawer_provider.dart';
// import 'View_model/Notification_dropdown_state.dart';
// import 'View_model/Sidebar_provider.dart';
// import 'View_model/Socket_Service.dart';
//
// void main() {
//   WidgetsFlutterBinding.ensureInitialized();
//   setUrlStrategy(PathUrlStrategy()); // ✅ Only applies on Web
//   final notificationState = NotificationState();
//   final socketService = SocketService(); // ✅ create instance
//
//
//   // ✅ Initialize Firebase
//   await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
//   );
//
//   runApp(
//     MultiProvider(
//       providers: [
//         ChangeNotifierProvider(create: (_) => SubDrawerProvider()),
//         ChangeNotifierProvider(create: (_) => SidedrawerProvider()),
//         ChangeNotifierProvider(create: (_) => AuthState()),
//         ChangeNotifierProvider(create: (_) => NotificationState()),
//         Provider<ApiClient>(
//           create: (context) => ApiClient(context.read<AuthState>()),
//         ),
//         Provider<SocketService>(
//           create: (_) {
//             const socketUrl = "https://3a986766-7c85-4976-a096-2068c43178dc-00-13z0wmt9o3tc5.pike.replit.dev:3000/";
//             return socketService..init(socketUrl, notifier: notificationState);
//           },
//         ),
//
//
//       ],
//       child: const MyApp(),
//     ),
//   );
// }
//
// class MyApp extends StatelessWidget {
//   const MyApp({super.key});
//
//   @override
//   Widget build(BuildContext context) {
//     return const MaterialApp(
//       debugShowCheckedModeBanner: false,
//       home: LoginPage(),
//     );
//   }
// }




import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_web_plugins/flutter_web_plugins.dart';
import 'package:firebase_core/firebase_core.dart'; // ✅ Required
import 'firebase_options.dart'; // ✅ Auto-generated by flutterfire CLI

import 'View/Login_page.dart';
import 'Services/api_client.dart';
import 'View_model/Authentication_state.dart';
import 'View_model/Drawer_provider.dart';
import 'View_model/Notification_dropdown_state.dart';
import 'View_model/Sidebar_provider.dart';
import 'View_model/Socket_Service.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  setUrlStrategy(PathUrlStrategy()); // ✅ Only applies on Web

  // ✅ Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final notificationState = NotificationState();
  final socketService = SocketService(); // ✅ create instance

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => SubDrawerProvider()),
        ChangeNotifierProvider(create: (_) => SidedrawerProvider()),
        ChangeNotifierProvider(create: (_) => AuthState()),
        ChangeNotifierProvider(create: (_) => NotificationState()),
        Provider<ApiClient>(
          create: (context) => ApiClient(context.read<AuthState>()),
        ),
        Provider<SocketService>(
          create: (_) {
            const socketUrl = "https://3a986766-7c85-4976-a096-2068c43178dc-00-13z0wmt9o3tc5.pike.replit.dev:3000/";
            return socketService..init(socketUrl, notifier: notificationState);
          },
        ),
      ],
      child: const MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: LoginPage(),
    );
  }
}
